namespace SmartParkingSystem.Domain.Models.DeviceConnection;

public sealed record DeviceControllerSnapshot(
    string Mode,
    int RemainingMs,
    bool Locked,
    bool ForceOpen,
    int OpenAngle,
    int ClosedAngle,
    int OpenDurationMs,
    int ThresholdCm,
    int TelemetryIntervalMs,
    bool GatePassageOccupied,
    int GatePassageDistanceCm,
    bool FrontAccessOccupied,
    int FrontAccessDistanceCm,
    int FrontAccessCounter,
    string DisplayText,
    bool DisplayForced,
    IReadOnlyList<DeviceSlotSnapshot> Slots,
    int AllowedCount,
    int BlockedCount,
    string LastAccessUid = "",
    string LastAccessResult = "",
    int LastAccessCounter = 0);
