namespace SmartParkingSystem.Models.Localization;

public sealed record MonitorTexts(
    string Title,
    string CurrentTextTitle,
    string ValidationHint,
    string RefreshButton,
    string SaveButton,
    string ResetButton,
    string ForceModeLabel,
    string ForcedTextLabel,
    string DefaultTextLabel,
    string AllowedTextLabel,
    string BlockedTextLabel,
    string InvalidTextLabel,
    string LockedTextLabel,
    string RefreshingMessage,
    string SavingMessage,
    string ResettingMessage,
    string RefreshSuccessMessage,
    string SaveSuccessMessage,
    string ResetSuccessMessage,
    string CurrentDisplayLabel,
    string ForceEnabledLabel,
    string ForceDisabledLabel)
{
    public MonitorTexts(
        string title,
        string currentTextTitle,
        string forceModeLabel,
        string forcedTextLabel,
        string defaultTextLabel,
        string allowedTextLabel,
        string blockedTextLabel,
        string invalidTextLabel,
        string lockedTextLabel,
        string saveButton,
        string refreshButton,
        string refreshingMessage,
        string savingMessage,
        string refreshSuccessMessage,
        string saveSuccessMessage,
        string currentDisplayLabel,
        string validationHint,
        string forceEnabledLabel,
        string forceDisabledLabel)
        : this(
            title,
            currentTextTitle,
            validationHint,
            refreshButton,
            saveButton,
            title == "Monitor" ? "Reset" : "Скинути",
            forceModeLabel,
            forcedTextLabel,
            defaultTextLabel,
            allowedTextLabel,
            blockedTextLabel,
            invalidTextLabel,
            lockedTextLabel,
            refreshingMessage,
            savingMessage,
            title == "Monitor" ? "Resetting monitor values..." : "Скидаємо значення монітора...",
            refreshSuccessMessage,
            saveSuccessMessage,
            title == "Monitor" ? "Monitor values restored" : "Значення монітора скинуто до стандартних",
            currentDisplayLabel,
            forceEnabledLabel,
            forceDisabledLabel)
    {
    }
}