namespace SmartParkingSystem.Domain.Models.Localization;

public sealed record MonitorTexts(
    string Title,
    string CurrentTextTitle,
    string ValidationHint,
    string RefreshButton,
    string SaveButton,
    string ResetButton,
    string ForceModeLabel,
    string ForcedTextLabel,
    string DefaultTextLabel,
    string AllowedTextLabel,
    string BlockedTextLabel,
    string InvalidTextLabel,
    string LockedTextLabel,
    string CameraLcdUnavailableTextLabel,
    string CameraLcdUnrecognizedTextLabel,
    string CameraLcdAiUnavailableTextLabel,
    string CameraLcdUnknownDeniedTextLabel,
    string CameraLcdAllowedTextLabel,
    string RefreshingMessage,
    string SavingMessage,
    string ResettingMessage,
    string RefreshSuccessMessage,
    string SaveSuccessMessage,
    string ResetSuccessMessage,
    string ForceEnabledLabel,
    string ForceDisabledLabel)
{
    public MonitorTexts(
        string title,
        string currentTextTitle,
        string forceModeLabel,
        string forcedTextLabel,
        string defaultTextLabel,
        string allowedTextLabel,
        string blockedTextLabel,
        string invalidTextLabel,
        string lockedTextLabel,
        string cameraLcdUnavailableTextLabel,
        string cameraLcdUnrecognizedTextLabel,
        string cameraLcdAiUnavailableTextLabel,
        string cameraLcdUnknownDeniedTextLabel,
        string cameraLcdAllowedTextLabel,
        string saveButton,
        string refreshButton,
        string refreshingMessage,
        string savingMessage,
        string refreshSuccessMessage,
        string saveSuccessMessage,
        string validationHint,
        string forceEnabledLabel,
        string forceDisabledLabel)
        : this(
            title,
            currentTextTitle,
            validationHint,
            refreshButton,
            saveButton,
            title == "Monitor" ? "Reset" : "Скинути",
            forceModeLabel,
            forcedTextLabel,
            defaultTextLabel,
            allowedTextLabel,
            blockedTextLabel,
            invalidTextLabel,
            lockedTextLabel,
            cameraLcdUnavailableTextLabel,
            cameraLcdUnrecognizedTextLabel,
            cameraLcdAiUnavailableTextLabel,
            cameraLcdUnknownDeniedTextLabel,
            cameraLcdAllowedTextLabel,
            refreshingMessage,
            savingMessage,
            title == "Monitor" ? "Resetting monitor values..." : "Скидаємо значення монітора...",
            refreshSuccessMessage,
            saveSuccessMessage,
            title == "Monitor" ? "Monitor values restored" : "Значення монітора скинуто до стандартних",
            forceEnabledLabel,
            forceDisabledLabel)
    {
    }
}
