namespace SmartParkingSystem.Domain.Models.Localization;

public sealed record SettingsTexts(
    string CurrentDeviceTitle,
    string InterfaceLanguageTitle,
    string EnvironmentTitle,
    string EditParkingLabel,
    string EnabledLabel,
    string DisabledLabel,
    string PlatformLabel,
    string ScreenLabel,
    string OsVersionLabel,
    string LocalizationLabel,
    string FrameworkLabel,
    string DotNetVersionLabel,
    string StylingLabel,
    string IconSystemLabel,
    string BackendTitle,
    string BackendSyncEnabledLabel,
    string BackendBaseUrlLabel,
    string BackendBaseUrlPlaceholder,
    string BackendTestingMessage,
    string BackendTestSuccessMessage,
    string BackendTestFailedMessage,
    string OpenAiUsageLabel,
    string OpenAiApiKeyLabel,
    string OpenAiTestingMessage,
    string TestConnectionButtonLabel);
