using SmartParkingSystem.Domain.Models.Localization;

namespace SmartParkingSystem.Maui.Services.Localization;

internal static partial class LocalizationTextCatalog
{
    private static readonly EventsTexts EnglishEventsTexts = new EventsTexts(
        "Events",
        "Search events",
        "All",
        "Connection",
        "Gate",
        "Parking",
        "Camera",
        "Monitor",
        "System",
        "No events yet",
        "Recent events are saved locally on this device",
        "Recent events",
        "Controller connected",
        "Controller disconnected",
        "Gate state changed",
        "Gate force-open changed",
        "Gate force-lock changed",
        "Gate open angle changed",
        "Gate closed angle changed",
        "Gate open duration changed",
        "Auto-open on exit changed",
        "Auto-close after passage changed",
        "Gate passage threshold changed",
        "Monitor force mode changed",
        "Monitor text changed",
        "Monitor text template changed: {0}",
        "Connection interval changed",
        "Parking threshold changed",
        "Slot {0} changed",
        "Slot {0} availability changed",
        "Camera snapshot captured",
        "Allowed cards changed",
        "Blocked cards changed",
        "Forced text",
        "Default text",
        "Allowed card text",
        "Blocked card text",
        "Invalid card text",
        "Locked text",
        "Enabled",
        "Disabled",
        "deg",
        "ms",
        "cm",
        "now",
        "s");

    private static readonly EventsTexts UkrainianEventsTexts = new EventsTexts(
        "Події",
        "Пошук подій",
        "Всі",
        "Зв'язок",
        "Ворота",
        "Паркінг",
        "Камера",
        "Монітор",
        "Система",
        "Поки що подій немає",
        "Останні події зберігаються локально на цьому пристрої",
        "Останні події",
        "Контролер підключено",
        "Контролер відключено",
        "Стан воріт змінено",
        "Примусове відкриття воріт змінено",
        "Примусове блокування воріт змінено",
        "Кут відкриття воріт змінено",
        "Кут закриття воріт змінено",
        "Час відкритих воріт змінено",
        "Автовідкриття на виїзд змінено",
        "Автозакриття після проїзду змінено",
        "Поріг датчика проїзду змінено",
        "Режим монітора змінено",
        "Текст монітора змінено",
        "Шаблон тексту монітора змінено: {0}",
        "Інтервал зв'язку змінено",
        "Поріг паркінгу змінено",
        "Слот {0} змінено",
        "Доступність слота {0} змінено",
        "Знімок камери зроблено",
        "Дозволені картки змінено",
        "Заблоковані картки змінено",
        "Примусовий текст",
        "Текст за замовчуванням",
        "Текст дозволеної картки",
        "Текст заблокованої картки",
        "Текст невірної картки",
        "Текст заблокованих воріт",
        "Увімкнено",
        "Вимкнено",
        "град",
        "мс",
        "см",
        "зараз",
        "с");

    public static EventsTexts GetEventsTexts(AppLanguage language)
    {
        return language == AppLanguage.Ukrainian ? UkrainianEventsTexts : EnglishEventsTexts;
    }
}
