using SmartParkingSystem.Domain.Models.Localization;

namespace SmartParkingSystem.Maui.Services.Localization;

internal static partial class LocalizationTextCatalog
{
    private static readonly EventsTexts EnglishEventsTexts = new EventsTexts(
        "Events",
        "Search events",
        "All",
        "Connection",
        "Gate",
        "Parking",
        "Monitor",
        "System",
        "No events yet",
        "Only events from the last two minutes are shown here",
        "Last 2 minutes",
        "Controller connected",
        "Controller disconnected",
        "Gate state changed",
        "Gate force-open changed",
        "Gate force-lock changed",
        "Gate open angle changed",
        "Gate closed angle changed",
        "Gate open duration changed",
        "Monitor force mode changed",
        "Monitor text changed",
        "Monitor text template changed: {0}",
        "Connection interval changed",
        "Parking threshold changed",
        "Slot {0} changed",
        "Slot {0} availability changed",
        "Allowed cards changed",
        "Blocked cards changed",
        "Forced text",
        "Default text",
        "Allowed card text",
        "Blocked card text",
        "Invalid card text",
        "Locked text",
        "Enabled",
        "Disabled",
        "deg",
        "ms",
        "cm",
        "now",
        "s");

    private static readonly EventsTexts UkrainianEventsTexts = new EventsTexts(
        "Події",
        "Пошук подій",
        "Всі",
        "Зв'язок",
        "Ворота",
        "Паркінг",
        "Монітор",
        "Система",
        "Поки що подій немає",
        "Тут показуються тільки події за останні 2 хвилини",
        "Останні 2 хвилини",
        "Контролер підключено",
        "Контролер відключено",
        "Стан воріт змінено",
        "Примусове відкриття воріт змінено",
        "Примусове блокування воріт змінено",
        "Кут відкриття воріт змінено",
        "Кут закриття воріт змінено",
        "Час відкритих воріт змінено",
        "Режим монітора змінено",
        "Текст монітора змінено",
        "Шаблон тексту монітора змінено: {0}",
        "Інтервал зв'язку змінено",
        "Поріг паркінгу змінено",
        "Слот {0} змінено",
        "Доступність слота {0} змінено",
        "Дозволені картки змінено",
        "Заблоковані картки змінено",
        "Примусовий текст",
        "Текст за замовчуванням",
        "Текст дозволеної картки",
        "Текст заблокованої картки",
        "Текст невірної картки",
        "Текст заблокованих воріт",
        "Увімкнено",
        "Вимкнено",
        "град",
        "мс",
        "см",
        "зараз",
        "с");

    public static EventsTexts GetEventsTexts(AppLanguage language)
    {
        return language == AppLanguage.Ukrainian ? UkrainianEventsTexts : EnglishEventsTexts;
    }
}